name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build and test steps here, if needed

      - name: Deploy to EC2
        run: |
          ssh -i ubuntu@65.0.71.130 'cd /var/www/html/ci-cd-practice && git checkout master && git pull origin master && sudo pm2 reload 0'
        env:
          SSH_PRIVATE_KEY: ${{ ec2-server-key }}
